### ISSUE TITLE
Таймзона при записи/просмотре доступного времени записи

### ISSUE THREAD

**Issue by rkrotov** [frolovelo/saloon_bot#2]
При просмотре записей на сегодня не учитывается таймзона, соответственно отображаются слоты, которые не должны.
в google_sheet.py

from pytz import timezone
tz = timezone("Europe/Moscow")

и все datetime.now() заменить на datetime.now(tz=tz)

Еще похоже ошибка в условии:
if v == client_record and k == date_today.time() < datetime.strptime(k, '%H:%M').time()
По итогу его просто убрал и расширил следующее, т.к. на сегодня логично видеть и записи в прошедшем времени (это спорная правка):
if date_today.date() <= date_sheet.date() <= (date_today + timedelta(days=count_days)).date():

**Comment by frolovelo** [comment]
Добавлю tz, спасибо

**Comment by frolovelo** [comment]
commit 4aa5acc
