### ISSUE TITLE
Сохранение словаря телефонов (костыль)

### ISSUE THREAD

**Issue by rkrotov** [frolovelo/saloon_bot#3]
Наверное и правда лучше это положить в sqlite в будущем, но пока сделал так, чтоб при каждом рестарте сервиса пользователям не требовалось отправлять повторно телефон.
в main.py
```
#CLIENT_PHONE = {613333839: '+79033333822'} #При первом запуске раскоментить
"""Функция сохранения в файл словаря клиентов"""
def save_clients():
    with open('clients.pkl', 'wb') as f:
        pickle.dump(CLIENT_PHONE, f)

#save_clients() #При первом запуске раскоментить

"""Функция загрузки из файла словаря клиентов"""
with open('clients.pkl', 'rb') as f:
    CLIENT_PHONE = pickle.load(f)
...............................
        @bot.message_handler(content_types=['contact']
...............
                save_clients()
                menu(message_contact)
```

**Comment by frolovelo** [comment]
ИМХО, у всех разные средства разработки, я, например, использую postgres или mongodb, а вам было бы удобнее видеть sqlite. Дабы упростить взаимодействие с данными я оставил простую конструкцию словаря, которую можно переложить на любую бд, которая вам по вкусу.
